SD-2853: add docs on how to use XFER
SparkPost/support-docs pull request #536
Opened 2021-09-02 19:58 UTC by pmcclory-sp

Document the XFER feature

2021-09-02 20:47 UTC, JohnPeacockMessageSystems requested changes

2021-09-02 20:47 UTC, JohnPeacockMessageSystems commented on momentum/4/outbound-xfer.md
> +To reroute messages for speicifc domains to an XFER server configuration like the following is needed:
speling

2021-09-02 20:47 UTC, JohnPeacockMessageSystems commented on momentum/4/outbound-xfer.md
> +To receive XFER messages from another server configuration like the following is needed:
subheading here for Receiving Server Setup?
```suggestion
### Server Config for Receiving XFer Messages
To receive XFER messages from another server configuration like the following is needed:
```

2021-09-02 20:47 UTC, JohnPeacockMessageSystems commented on momentum/4/outbound-xfer.md
> +To reroute delayed messages to an XFER server configuration like the following is needed (assuming the XFER server is running on 10.10.10.10):
```suggestion
### Sending Server for XFer Delayed Messages
To reroute delayed messages to an XFER server configuration like the following is needed (assuming the XFER server is running on 10.10.10.10):
```

2021-09-02 20:47 UTC, JohnPeacockMessageSystems commented on momentum/4/outbound-xfer.md
> +To reroute messages for speicifc domains to an XFER server configuration like the following is needed:
```suggestion
### Sending Server Config for Specific Domains
To reroute messages for specific domains to an XFER server configuration like the following is needed:
```

2021-09-02 20:48 UTC, mdyer-sparkpost requested changes

2021-09-02 20:48 UTC, mdyer-sparkpost commented on momentum/4/outbound-xfer.md
> +To receive XFER messages from another server configuration like the following is needed:
Nitpick
```suggestion
To receive XFER messages from another server, configuration like the following is needed:
```

2021-09-02 20:48 UTC, mdyer-sparkpost commented on momentum/4/outbound-xfer.md
> +To reroute delayed messages to an XFER server configuration like the following is needed (assuming the XFER server is running on 10.10.10.10):
Aanother nitpick
```suggestion
To reroute delayed messages to an XFER server, configuration like the following is needed (assuming the XFER server is running on 10.10.10.10):
```

2021-09-02 20:48 UTC, mdyer-sparkpost commented on momentum/4/outbound-xfer.md
> +To reroute messages for speicifc domains to an XFER server configuration like the following is needed:
Typo fix
```suggestion
To reroute messages for specifc domains to an XFER server, configuration like the following is needed:
```

2021-09-03 13:07 UTC, mdyer-sparkpost approved these changes

2021-09-03 14:17 UTC, JohnPeacockMessageSystems approved these changes

2021-09-03 14:18 UTC, merged