WE-164 style side navigation menu
SparkPost/support-docs pull request #578
Opened 2021-10-29 16:52 UTC by logansparlin

## What Changed
- Adds styling and expanding functionality to the side navigation

## How to verify
- Run locally or visit the deploy link to verify the styling and functionality are correct

2021-10-29 22:00 UTC, EvanYoung-SP requested changes
Just a few changes, but great work!

2021-11-01 12:57 UTC, jonambas reviewed
not sure if you saw, but there are some cypress screenshots in this PR

2021-11-01 16:44 UTC, logansparlin commented on components/site/momentumNavigation.tsx
> +const StyledLink = styled(Box)<BoxProps & { $active?: boolean }>`
That way styled components doesn't pass active in as an html attribute

2021-11-01 19:45 UTC, EvanYoung-SP approved these changes
LGTM!

2021-11-01 20:33 UTC, merged