WE-304 Direct copy pasta from main
SparkPost/support-docs pull request #616
Opened 2021-11-19 13:51 UTC by jonambas

### Support Docs Update Checklist

Note: when you open a pull request, your changes are published to https://staging.sparkpost.com/docs.

Please take a moment to check each of these steps for your pull request:

- [ ] Give your pull request a meaningful name.
- [ ] Include a description of your changes in the pull request.
- [ ] _SparkPost staff only_: Check that your article appears [here](https://staging.sparkpost.com/docs) and looks correct.
- [ ] Check the links in your article.
- [ ] Use lowercase filenames.

2021-11-19 23:39 UTC, EvanYoung-SP requested changes
A few changes will need to be made since they're undoing the intentional changes made in a previous PR. Not a big deal.
 https://github.com/SparkPost/support-docs/pull/612/files

2021-11-19 23:39 UTC, EvanYoung-SP commented on content/momentum/3/index.md
> +* * *
This change is undoing some of the changes made here: https://github.com/SparkPost/support-docs/pull/612/files

2021-11-19 23:39 UTC, EvanYoung-SP commented on content/momentum/4/index.md
> +lastUpdated: "03/26/2020"
This change is undoing some of the changes made here: https://github.com/SparkPost/support-docs/pull/612/files

2021-11-19 23:39 UTC, EvanYoung-SP commented on content/momentum/changelog/index.md
> +* [Legacy Momentum Changelogs](/momentum/changelog/legacy)
This change is undoing some of the changes made here: https://github.com/SparkPost/support-docs/pull/612/files

2021-11-19 23:39 UTC, EvanYoung-SP commented on content/momentum/mobile/index.md
> +This book is an administration guide for Mobile Momentum.
This change is undoing some of the changes made here: https://github.com/SparkPost/support-docs/pull/612/files

2021-11-22 13:52 UTC, jonambas commented
@EvanYoung-SP waiting for #614 to be merged before i finish up this one, since there are content changes in that PR

2021-11-22 21:30 UTC, EvanYoung-SP approved these changes
LGTM!

2021-11-22 21:34 UTC, merged